ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'WAREHOUSE_MANAGER';
ALTER TYPE "SupplyRequestStatus" ADD VALUE IF NOT EXISTS 'PENDING_WAREHOUSE_MANAGER';
ALTER TYPE "ApprovalAction" ADD VALUE IF NOT EXISTS 'SENT_TO_WAREHOUSE_MANAGER';
