ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'WORKSHOP_MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'DEPUTY_PRODUCTION_DIRECTOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'GARAGE_MANAGER';

ALTER TYPE "ObjectType" ADD VALUE IF NOT EXISTS 'WORKSHOP';

ALTER TYPE "SupplyRequestStatus" ADD VALUE IF NOT EXISTS 'PENDING_DEPUTY_PRODUCTION_DIRECTOR';
ALTER TYPE "SupplyRequestStatus" ADD VALUE IF NOT EXISTS 'PENDING_GARAGE_MANAGER';
