ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'STOREKEEPER';
ALTER TYPE "SupplyRequestStatus" ADD VALUE IF NOT EXISTS 'PENDING_STOREKEEPER';
ALTER TYPE "ApprovalAction" ADD VALUE IF NOT EXISTS 'SENT_TO_STOREKEEPER';
